path:
  training_set: ../MICCAI_BraTS_2018_Data_Training.zip
  validation_set: ../MICCAI_BraTS_2018_Data_Validation.zip
  best_model: ../best_model/model # this is used for resuming the training
  checkpoint: ../checkpoint/model # to save best model in the training process
  last_model: ../checkpoint/last/model # to save last model in the training process

preprocessing_seg: # preprocessing during segmentation
  min_max: false
  bias_correction: false
  adaptive: false
  optimal_roi:
    - 128  # dim 0
    - 128  # dim 1
    - 128  # dim 2

data_augmentation:
  brightness:
    enable: true
    limit: 0.6
  elastic_deform:
    enable: true
    limit: 0.6

model:
  accumulated_grad:
    enable: true
    num_batch: 8

training:
  resume_training: true
  lr: 1e-4
  batch_size: 1
  number_fold: 5  # K fold cross validation
  epochs_per_fold: 1 # number of epochs per fold

genetic:
  w1: 0.8  # weight for accuracy
  w2: -0.2  # weight for run time
  pc: 0.9  # higher cross over probability --> more exploitation
  pm: 0.1  # higher mutation probability --> more exploration
  itr_threshold: 25
  gen_threshold: 4  # if the best member didn't change, this parameter would stop the algorithm
  version: third # quarter vs third : how much of the model should be pruned
